slide1: "vietsukieuhung1.jpg"
slide2: "vietsukieuhung2.jpg"
slide3: "vietsukieuhung3.jpg"
location: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.3993006915894!2d105.7813909498774!3d21.01670319349843!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam%20Hanoi%20Landmark%20Tower!5e0!3m2!1svi!2s!4v1583137453429!5m2!1svi!2s"
lastest_trailer: "movie1.jpg"
most_comment: "movie10.jpg"
top_rated: "movie2.jpg"
image_default: "https://ssl.gstatic.com/accounts/ui/avatar_2x.png"
limmit_category: 25
take_category: 3
limmit_films_home: 5
search_films: 10
category_home: 7
release_date: "%d/%m/%Y - %H:%M"
numericality: 1
image_default: "https://image.shutterstock.com/z/stock-vector-default-avatar-profile-icon-grey-photo-placeholder-hand-drawn-modern-man-avatar-profile-icon-1545687092.jpg"
textarea_row: 4
